#!/bin/sh

CACHE="/var/spool/squid"
PID=`cat /var/run/squid.pid 2>/dev/null`

if test -n "$PID"; then
   systemctl stop squid.service
   if [ -d "$CACHE" ]
   then
   mv $CACHE $CACHE.old
   mkdir $CACHE
   chown -R proxy:proxy $CACHE
   squid -z
   systemctl restart squid.service
   rm -rf $CACHE.old
   fi
else
   if [ -d "$CACHE" ]
   then
   mv $CACHE $CACHE.old
   mkdir $CACHE
   chown -R proxy:proxy $CACHE
   squid -z
   rm -rf $CACHE.old
   fi
fi
